name: run-script-os CICD

on: [push]

jobs:
  test:
    name: Test on different OSes and Node versions
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./tests
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node-version:
          #- 12
          - 14
    steps:
      - uses: actions/checkout@v2
      - name: Testing run-script-os with Node.js ${{ matrix.node-version }} on ${{ matrix.os }} from a tests project similar to how run-script-os is used by others.
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Starting NPM version
        run: npm --version
      - name: Installing node modules for the tests (working-directory is ./tests)
        run: npm ci
      - name: Running tests
        run: npm test
      - name: Update NPM to the latest version
        run: npm install -g npm@latest
      - name: Latest NPM version
        run: npm --version
      - name: Running tests at latest NPM version
        run: npm test
      - name: Update NPM to the latest version
        run: npm install -g npm@next
      - name: Latest NPM version
        run: npm --version
      - name: Running tests at latest NPM version
        run: npm test
  deploy:
    name: Publish to NPM
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Testing run-script-os with Node.js ${{ matrix.node-version }} on ${{ matrix.os }} from a tests project similar to how run-script-os is used by others.
        uses: actions/setup-node@v2
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
