name: run-script-os CICD

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./tests
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node-version:
          - 12
          - 14
    steps:
      - uses: actions/checkout@v2
      - name: Testing run-script-os with Node.js ${{ matrix.node-version }} on ${{ matrix.os }} from a tests project similar to how run-script-os is used by others.
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing node modules for the tests (working-directory is ./tests)
        run: npm ci
      - name: Running tests
        run: npm test
  deploy:
    name: Publish to NPM
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    #timeout-minutes: 3
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Testing run-script-os with Node.js ${{ matrix.node-version }} on ${{ matrix.os }} from a tests project similar to how run-script-os is used by others.
        uses: actions/setup-node@v2
      - name: Check line endings
        run: file *
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true
